### ISSUE TITLE
AttributeError: 'PeerSelfLocated' object has no attribute 'distance'

### ISSUE THREAD

**Issue by maaxx0** [IvanGlinkin/CCTV#15]
What i get when i run the code 
**i tried different OS but still same problem** 
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/gehrman/Downloads/CCTV-main/start.py", line 174, in <module>
    if peer_located.distance == 500:
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PeerSelfLocated' object has no attribute 'distance'

```

**Comment by IvanGlinkin** [comment]
Close as duplicated -> https://github.com/IvanGlinkin/CCTV/issues/12
