### ISSUE TITLE
where to create `config.yaml` ?

### ISSUE THREAD

**Issue by wzzjhc** [IvanGlinkin/CCTV#44]
```
I put the file 'config.yaml' in the root directory with 'start.py'

I also noticed that my Telegram API prompts 'It is forbidden to pass this value to third parties.'

I don't know what to do next?
``` 
[root@XXXXX CCTV]# python3 start.py
Traceback (most recent call last):
  File "start.py", line 12, in <module>
    from backend.banners import (
  File "/root/CCTV/backend/banners.py", line 1, in <module>
    from .functions import get_location_details
  File "/root/CCTV/backend/functions.py", line 8, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by wzzjhc** [comment]
O~K
